# Site settings
title: t0nylombardi
description: 't0nylombardi.com blog'
url: 'http://t0nylombardi.com/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'T0ny Lombardi'
  email: me@t0nylombardi.com
  twitter_username: t0nylombardi
  facebook_username:
  github_username:  t0nylombardi
  linkedin_username:  anthonyjlombardi

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: [jekyll-paginate, 'jekyll-gist']
paginate: 10
paginate_path: "page:num"

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
